<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>homework1</RootNamespace>
        <DefaultItemExcludes>$(DefaultItemExcludes);BookStoreApi\**</DefaultItemExcludes>

    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="BookStoreApi\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="BookStoreApi\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="BookStoreApi\**" />
    </ItemGroup>

</Project>
